### GET ALL CLASSES
GET http://[::1]:3000/classes HTTP/1.1

### GET SINGLE CLASS
GET http://[::1]:3000/classes/2 HTTP/1.1

### ADD SINGLE CLASS
POST http://[::1]:3000/classes HTTP/1.1
Content-Type: application/json

{
    "class_name": "Biology",
    "class_teacher_id": "2",
    "student_list": ["Lavitra Misal", "Sahil Hemnani"]
}

### DELETE SINGLE CLASS
DELETE  http://[::1]:3000/classes/2 HTTP/1.1

### UPDATE SINGLE CLASS
PUT http://[::1]:3000/classes/1 HTTP/1.1
Content-Type: application/json

{
    "class_name": "Science",
    "class_teacher_id": "4",
    "student_list": ["Ashutosh Manorkar", "Sahil Hemnani"]
}
